### ISSUE TITLE
Unable to inject asmble.compile.jvm.Insn$ThisNeededOnStack

### ISSUE THREAD

**Issue by tbutter** [cretz/asmble#2]
It think the stack diff for GetGlobal should be 1 since "this" is inserted here https://github.com/cretz/asmble/blob/da1d94dc9eccc30e2c804e6e8287dabbe25ac707/src/main/kotlin/asmble/compile/jvm/FuncBuilder.kt#L1149 (but I am not sure if I understood the algorithm correctly). It seems to work when i remove the POP_THIS in insnStackDiff().

        is Node.Instr.GetGlobal -> POP_THIS + PUSH_RESULT
changed to
        is Node.Instr.GetGlobal -> PUSH_RESULT

Here is the function I tried to compile with the trace (happens with any wasm file from ogv.js):
```
[TRACE] Stack diff is 0 for GetGlobal(index=4)
[TRACE] Stack diff is 0 for GetGlobal(index=4)
[TRACE] Stack diff is 1 for I32Const(value=1027)
[TRACE] Stack diff is 1 for I32Const(value=2272)
[TRACE] Stack diff is 1 for I32Const(value=7356)
[TRACE] Stack diff is 1 for I32Const(value=7408)
[TRACE] Stack diff is 1 for I32Const(value=7460)
[TRACE] Stack diff is 1 for I32Const(value=7512)
[TRACE] Stack diff is 1 for I32Const(value=18792)
[TRACE] Stack diff is 1 for I32Const(value=18848)
[TRACE] Stack diff is 1 for I32Const(value=19906)
[TRACE] Stack diff is 1 for I32Const(value=19956)
[TRACE] Stack diff is 1 for I32Const(value=19990)
[TRACE] Stack diff is 1 for I32Const(value=25441)
[TRACE] Stack diff is 1 for I32Const(value=25462)
[DEBUG] Building function $func13
[TRACE] Function ast:
(func
  (param i32)
  (result i32)
  (local i32)
  (block i32)
  (get_global 6)
  (set_local 1)
  (get_global 6)
  (get_local 0)
  (i32.add)
  (set_global 6)
  (get_global 6)
  (i32.const 15)
  (i32.add)
  (i32.const -16)
  (i32.and)
  (set_global 6)
  (get_local 1)
  (end)
)
[TRACE] Stack diff is 0 for Block(type=asmble.ast.Node$Type$Value$I32@5a5a729f)
[TRACE] Stack diff is 0 for GetGlobal(index=6)
[TRACE] Stack diff is -1 for SetLocal(index=1)
[TRACE] Stack diff is 0 for GetGlobal(index=6)
[TRACE] Stack diff is 1 for GetLocal(index=0)
[TRACE] Stack diff is -1 for asmble.ast.Node$Instr$I32Add@4b520ea8
[TRACE] Injecting asmble.compile.jvm.Insn$ThisNeededOnStack@782859e back 1 stack values
[ERROR] Error in command 'compile': Unable to inject asmble.compile.jvm.Insn$ThisNeededOnStack@782859e back 1 stack values
asmble.compile.jvm.CompileErr$StackInjectionMismatch: Unable to inject asmble.compile.jvm.Insn$ThisNeededOnStack@782859e back 1 stack values
	at asmble.compile.jvm.InsnReworker$injectNeededStackVars$1.invoke(InsnReworker.kt:127)
	at asmble.compile.jvm.InsnReworker.injectNeededStackVars(InsnReworker.kt:149)
	at asmble.compile.jvm.InsnReworker.rework(InsnReworker.kt:8)
	at asmble.compile.jvm.FuncBuilder.fromFunc(FuncBuilder.kt:29)
	at asmble.compile.jvm.AstToAsm.addFuncs(AstToAsm.kt:516)
	at asmble.compile.jvm.AstToAsm.fromModule(AstToAsm.kt:20)
	at asmble.cli.Compile.run(Compile.kt:58)
	at asmble.cli.Compile.run(Compile.kt:10)
	at asmble.cli.Command.runWithArgs(Command.kt:17)
	at asmble.cli.MainKt.main(Main.kt:31)
```

**Comment by cretz** [comment]
Hrmm, this might indeed be correct. I will put together a use case based on your code (or you can if you'd like) and confirm the stack diff should indeed by +1 on get_global (not 0) which it probably should be, and should be -1 not -1 for set_global.

**Comment by cretz** [comment]
All fixed, thanks again!
