### ISSUE TITLE
asmble run wasm file failed

### ISSUE THREAD

**Issue by lidulibai** [cretz/asmble#27]
[ERROR] Error in command 'invoke': Failed loading .\basic.wasm - lateinit property logger has not been initialized
java.lang.Exception: Failed loading .\basic.wasm - lateinit property logger has not been initialized
        at asmble.cli.ScriptCommand.prepareContext(ScriptCommand.kt:73)
        at asmble.cli.Invoke.run(Invoke.kt:37)
        at asmble.cli.Invoke.run(Invoke.kt:6)
        at asmble.cli.Command.runWithArgs(Command.kt:17)
        at asmble.cli.MainKt.main(Main.kt:31)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property logger has not been initialized
        at asmble.cli.Command.getLogger(Command.kt:9)
        at asmble.cli.Translate.inToAst(Translate.kt:70)
        at asmble.cli.ScriptCommand.prepareContext(ScriptCommand.kt:60)
        ... 4 more

**Comment by cretz** [comment]
Thanks for the report, to confirm, are you using master branch or a release download? What is the exact command you are running?

**Comment by lidulibai** [comment]
Thanks for your reply,
the release download asmble.zip file:
command > asmble invoke -res -in basic.wasm main
and the master branch source file
command > gradle run --args="invoke -res -in basic.wasm main"

**Comment by cretz** [comment]
Ah yes, invoke may have broken. It's not a very practical command for WASM use, I might just get rid of it. Will take a peek in the coming days.

**Comment by lidulibai** [comment]
Thanks a lot
