### ISSUE TITLE
Error in command 'compile': Class too large: MyClass

### ISSUE THREAD

**Issue by MihaelIsaev** [cretz/asmble#41]
Hello, I'm trying to compile wasm file which contains Swift app inside and getting `Class too large` error.

```
org.objectweb.asm.ClassTooLargeException: Class too large: MyClass
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:550)
	at asmble.compile.jvm.AsmToBinary.fromClassNode(AsmToBinary.kt:30)
	at asmble.compile.jvm.AsmToBinary.fromClassNode$default(AsmToBinary.kt:21)
	at asmble.cli.Compile.run(Compile.kt:72)
	at asmble.cli.Compile.run(Compile.kt:10)
	at asmble.cli.Command.runWithArgs(Command.kt:17)
	at asmble.cli.MainKt.main(Main.kt:31)
```

The wasm file is in attach.

Is there any chance to pass this limitation?
[aaa.wasm.zip](https://github.com/cretz/asmble/files/6767493/aaa.wasm.zip)

**Comment by cretz** [comment]
Looks like just too many constants. I'd have to dig into seeing what constants asmble is generating, but short of changing how asmble works, I don't think there's an easy fix.
