### ISSUE TITLE
No opcode found: 252

### ISSUE THREAD

**Issue by moritzfl** [cretz/asmble#46]
When trying to compile [pdfcpu](https://github.com/pdfcpu/pdfcpu) from webassembly to Java, I get the following error (I tried the release for Version 0.8.0):

```
asmble compile ./pdfcpu.wasm -format wasm PdfCpu -log info
[ERROR] Error in command 'compile': No opcode found: 252
java.lang.IllegalStateException: No opcode found: 252
        at asmble.ast.Node$InstrOp$Companion.op(Node.kt:456)
        at asmble.io.BinaryToAst.toInstr(BinaryToAst.kt:119)
        at asmble.io.BinaryToAst.toInstrs(BinaryToAst.kt:117)
        at asmble.io.BinaryToAst.toFunc(BinaryToAst.kt:78)
        at asmble.io.BinaryToAst.toModule(BinaryToAst.kt:209)
        at asmble.cli.Translate.inToAst(Translate.kt:70)
        at asmble.cli.Compile.run(Compile.kt:54)
        at asmble.cli.Compile.run(Compile.kt:10)
        at asmble.cli.Command.runWithArgs(Command.kt:17)
        at asmble.cli.MainKt.main(Main.kt:31)
```

According to https://pengowray.github.io/wasm-ops/ this means that FC extensions (Multibyte instructions beginning with 0xFC.) are used.

Is it feasible to add support for this in asmble?

**Comment by cretz** [comment]
I don't work on this project much anymore, so it is unlikely I'll be adding support for any new opcodes anytime soon
